disabled_rules:
  - trailing_whitespace
  - function_body_length
  - line_length
  - orphaned_doc_comment
  - nesting

opt_in_rules:
  - let_var_whitespace

included:
  - InstagramFirestoreTutorial
excluded:
  # AppDelegate, SceneDelegate file 무시
  - InstagramFirestoreTutorial/AppDelegate.swift
  - InstagramFirestoreTutorial/SceneDelegate.swift

identifier_name:
  excluded:
    - id

force_cast: warning
